# Generated by Django 3.2.21 on 2023-09-22 13:14

import django.db.models.deletion
from django.db import migrations, models

import baserow.core.fields
import baserow.core.formula.field
import baserow.core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0021_alter_domain_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderWorkflowAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", baserow.core.fields.SyncedDateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[("click", "Click")],
                        help_text="The event that triggers the execution",
                        max_length=30,
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.element",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                baserow.core.mixins.PolymorphicContentTypeMixin,
                baserow.core.mixins.OrderableMixin,
                models.Model,
                baserow.core.mixins.WithRegistry,
            ),
        ),
        migrations.CreateModel(
            name="NotificationWorkflowAction",
            fields=[
                (
                    "builderworkflowaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.builderworkflowaction",
                    ),
                ),
                ("title", baserow.core.formula.field.FormulaField(default="")),
                ("description", baserow.core.formula.field.FormulaField(default="")),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.builderworkflowaction",),
        ),
    ]
