# Generated by Django 3.2.21 on 2023-09-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('builder', '0022_builderworkflowaction_notificationworkflowaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderworkflowaction',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='builder_workflow_actions', to='contenttypes.contenttype', verbose_name='content type'),
            preserve_default=False,
        ),
    ]
