# Generated by Django 3.2.21 on 2023-09-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_builderworkflowaction_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderworkflowaction',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='builder.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builderworkflowaction',
            name='element',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.element'),
        ),
    ]
