# Generated by Django 3.2.21 on 2023-10-04 12:27

import baserow.core.formula.field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0023_builderworkflowaction_notificationworkflowaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPageWorkflowAction",
            fields=[
                (
                    "builderworkflowaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="builder.builderworkflowaction",
                    ),
                ),
                ("url", baserow.core.formula.field.FormulaField(default="")),
            ],
            options={
                "abstract": False,
            },
            bases=("builder.builderworkflowaction",),
        ),
    ]
