# Generated by Django 3.2.21 on 2023-11-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0028_add_collection_field_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.element')),
            ],
            options={
                'abstract': False,
            },
            bases=('builder.element',),
        ),
    ]
