# Generated by Django 3.2.21 on 2023-12-05 14:53

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0031_auto_20231205_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropdownelementoption",
            name="name",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", help_text="The display name of the option"
            ),
        ),
        migrations.AlterField(
            model_name="dropdownelementoption",
            name="value",
            field=baserow.core.formula.field.FormulaField(
                blank=True, default="", help_text="The value of the option"
            ),
        ),
    ]
