# Generated by Django 3.2.21 on 2023-11-30 15:07

from django.db import migrations

import baserow.core.formula.field


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0032_alter_formcontainerelement_submit_button_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formcontainerelement",
            name="submit_button_label",
            field=baserow.core.formula.field.FormulaField(default="'Submit'"),
        ),
    ]
