# Generated by Django 3.2.20 on 2023-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0124_add_encode_uri_component_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportjob',
            name='ai_description',
            field=models.TextField(default=None, help_text='An AI description of what the table data should look like.', null=True),
        ),
    ]
