# Generated by Django 3.2.21 on 2023-09-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0127_viewgroupby"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewFilterGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all the rows should apply to all filters (AND) or to any filter (OR).",
                        max_length=3,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.viewfiltergroup",
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        help_text="The view to which the filter applies. Each view can have his own filters.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.view",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="viewfilter",
            name="view_filter_group",
            field=models.ForeignKey(
                help_text="The view to which the filter applies. Each view can have his own filters.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database.viewfiltergroup",
            ),
        ),
    ]
