# Generated by Django 3.2.21 on 2023-09-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0128_add_view_filter_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormViewFieldOptionsConditionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[("AND", "And"), ("OR", "Or")],
                        default="AND",
                        help_text="Indicates whether all (AND) or any (OR) of the conditions should match before shown.",
                        max_length=3,
                    ),
                ),
                (
                    "field_option",
                    models.ForeignKey(
                        help_text="The form view option where the condition is related to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_groups",
                        to="database.formviewfieldoptions",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.formviewfieldoptionsconditiongroup",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="formviewfieldoptionscondition",
            name="filter_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="database.formviewfieldoptionsconditiongroup",
            ),
        ),
    ]
