# Generated by Django 3.2.21 on 2023-10-09 10:17

import baserow.core.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_template_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.CharField(default=baserow.core.services.models.generate_uuid, max_length=36, null=True),
        ),
    ]
